from odoo import models, fields


class AiChatMessage(models.Model):
    _name = 'ai.chat.message'
    _description = 'AI Chat Message'
    _order = 'id asc'

    conversation_id = fields.Many2one(
        'ai.chat.conversation',
        required=True,
        ondelete='cascade',
        help="Conversation to which this message belongs.",
    )

    role = fields.Selection(
        [
            ('user', 'User'),
            ('assistant', 'Assistant'),
        ],
        required=True,
        default='user',
        help="Indicates whether the message was sent by the user or generated by the AI assistant.",
    )

    content = fields.Text(
        required=True,
        help="Text content of the conversation message.",
    )

    create_date = fields.Datetime(
        readonly=True,
        help="Date and time when the message was created.",
    )
